package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.ProductSku;
import com.ailk.ts.dal.ibatis.model.ProductSkuExample;
import java.util.List;

public interface ProductSkuDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int countByExample(ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int deleteByExample(ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer skuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    Integer insert(ProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    Integer insertSelective(ProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    List<ProductSku> selectByExample(ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    ProductSku selectByPrimaryKey(Integer skuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int updateByExampleSelective(ProductSku record, ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int updateByExample(ProductSku record, ProductSkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductSku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductSku record);
}