package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.ProductSku;
import com.ailk.ts.dal.ibatis.model.ProductSkuExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductSkuDAOImpl extends SqlMapClientDaoSupport implements ProductSkuDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public ProductSkuDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int countByExample(ProductSkuExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("product_sku.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int deleteByExample(ProductSkuExample example) {
        int rows = getSqlMapClientTemplate().delete("product_sku.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Integer skuid) {
        ProductSku _key = new ProductSku();
        _key.setSkuid(skuid);
        int rows = getSqlMapClientTemplate().delete("product_sku.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public Integer insert(ProductSku record) {
        Object newKey = getSqlMapClientTemplate().insert("product_sku.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public Integer insertSelective(ProductSku record) {
        Object newKey = getSqlMapClientTemplate().insert("product_sku.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public List<ProductSku> selectByExample(ProductSkuExample example) {
        List<ProductSku> list = getSqlMapClientTemplate().queryForList("product_sku.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public ProductSku selectByPrimaryKey(Integer skuid) {
        ProductSku _key = new ProductSku();
        _key.setSkuid(skuid);
        ProductSku record = (ProductSku) getSqlMapClientTemplate().queryForObject("product_sku.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int updateByExampleSelective(ProductSku record, ProductSkuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("product_sku.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int updateByExample(ProductSku record, ProductSkuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("product_sku.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(ProductSku record) {
        int rows = getSqlMapClientTemplate().update("product_sku.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(ProductSku record) {
        int rows = getSqlMapClientTemplate().update("product_sku.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends ProductSkuExample {
        private Object record;

        public UpdateByExampleParms(Object record, ProductSkuExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}