package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.Rep;
import com.ailk.ts.dal.ibatis.model.RepExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RepDAOImpl extends SqlMapClientDaoSupport implements RepDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public RepDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int countByExample(RepExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("rep.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int deleteByExample(RepExample example) {
        int rows = getSqlMapClientTemplate().delete("rep.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Integer id) {
        Rep _key = new Rep();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("rep.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public Integer insert(Rep record) {
        Object newKey = getSqlMapClientTemplate().insert("rep.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public Integer insertSelective(Rep record) {
        Object newKey = getSqlMapClientTemplate().insert("rep.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public List<Rep> selectByExample(RepExample example) {
        List<Rep> list = getSqlMapClientTemplate().queryForList("rep.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public Rep selectByPrimaryKey(Integer id) {
        Rep _key = new Rep();
        _key.setId(id);
        Rep record = (Rep) getSqlMapClientTemplate().queryForObject("rep.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int updateByExampleSelective(Rep record, RepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("rep.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int updateByExample(Rep record, RepExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("rep.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(Rep record) {
        int rows = getSqlMapClientTemplate().update("rep.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(Rep record) {
        int rows = getSqlMapClientTemplate().update("rep.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rep
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends RepExample {
        private Object record;

        public UpdateByExampleParms(Object record, RepExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}