package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.Rep;
import com.ailk.ts.dal.ibatis.model.RepExample;
import java.util.List;

public interface RepDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int countByExample(RepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int deleteByExample(RepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    Integer insert(Rep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    Integer insertSelective(Rep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    List<Rep> selectByExample(RepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    Rep selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int updateByExampleSelective(Rep record, RepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int updateByExample(Rep record, RepExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Rep record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Rep record);
}