package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.Repository;
import com.ailk.ts.dal.ibatis.model.RepositoryExample;
import java.util.List;

public interface RepositoryDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int countByExample(RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int deleteByExample(RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long repCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    Long insert(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    Long insertSelective(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    List<Repository> selectByExample(RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    Repository selectByPrimaryKey(Long repCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int updateByExampleSelective(Repository record, RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int updateByExample(Repository record, RepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Repository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table repository
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Repository record);
}