package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.RepOptRecord;
import com.ailk.ts.dal.ibatis.model.RepOptRecordExample;
import java.util.List;

public interface RepOptRecordDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int countByExample(RepOptRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int deleteByExample(RepOptRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer serialNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    Integer insert(RepOptRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    Integer insertSelective(RepOptRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    List<RepOptRecord> selectByExample(RepOptRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    RepOptRecord selectByPrimaryKey(Integer serialNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(RepOptRecord record, RepOptRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int updateByExample(RepOptRecord record, RepOptRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RepOptRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_opt_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RepOptRecord record);
}