package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.RepSellDetail;
import com.ailk.ts.dal.ibatis.model.RepSellDetailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RepSellDetailDAOImpl extends SqlMapClientDaoSupport implements RepSellDetailDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public RepSellDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int countByExample(RepSellDetailExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("rep_sell_detail.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int deleteByExample(RepSellDetailExample example) {
        int rows = getSqlMapClientTemplate().delete("rep_sell_detail.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Integer rid) {
        RepSellDetail _key = new RepSellDetail();
        _key.setRid(rid);
        int rows = getSqlMapClientTemplate().delete("rep_sell_detail.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public Integer insert(RepSellDetail record) {
        Object newKey = getSqlMapClientTemplate().insert("rep_sell_detail.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public Integer insertSelective(RepSellDetail record) {
        Object newKey = getSqlMapClientTemplate().insert("rep_sell_detail.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public List<RepSellDetail> selectByExample(RepSellDetailExample example) {
        List<RepSellDetail> list = getSqlMapClientTemplate().queryForList("rep_sell_detail.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public RepSellDetail selectByPrimaryKey(Integer rid) {
        RepSellDetail _key = new RepSellDetail();
        _key.setRid(rid);
        RepSellDetail record = (RepSellDetail) getSqlMapClientTemplate().queryForObject("rep_sell_detail.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int updateByExampleSelective(RepSellDetail record, RepSellDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("rep_sell_detail.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int updateByExample(RepSellDetail record, RepSellDetailExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("rep_sell_detail.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(RepSellDetail record) {
        int rows = getSqlMapClientTemplate().update("rep_sell_detail.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(RepSellDetail record) {
        int rows = getSqlMapClientTemplate().update("rep_sell_detail.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends RepSellDetailExample {
        private Object record;

        public UpdateByExampleParms(Object record, RepSellDetailExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}