package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.SkuEntity;
import com.ailk.ts.dal.ibatis.model.SkuEntityExample;
import java.util.List;

public interface SkuEntityDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int countByExample(SkuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int deleteByExample(SkuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer entityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    Integer insert(SkuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    Integer insertSelective(SkuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    List<SkuEntity> selectByExample(SkuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    SkuEntity selectByPrimaryKey(Integer entityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(SkuEntity record, SkuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int updateByExample(SkuEntity record, SkuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SkuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SkuEntity record);
}