package com.ailk.ts.dal.ibatis;

import com.ailk.ts.dal.ibatis.model.SkuEntity;
import com.ailk.ts.dal.ibatis.model.SkuEntityExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SkuEntityDAOImpl extends SqlMapClientDaoSupport implements SkuEntityDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public SkuEntityDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int countByExample(SkuEntityExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("sku_entity.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int deleteByExample(SkuEntityExample example) {
        int rows = getSqlMapClientTemplate().delete("sku_entity.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int deleteByPrimaryKey(Integer entityId) {
        SkuEntity _key = new SkuEntity();
        _key.setEntityId(entityId);
        int rows = getSqlMapClientTemplate().delete("sku_entity.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public Integer insert(SkuEntity record) {
        Object newKey = getSqlMapClientTemplate().insert("sku_entity.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public Integer insertSelective(SkuEntity record) {
        Object newKey = getSqlMapClientTemplate().insert("sku_entity.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    @SuppressWarnings("unchecked")
    public List<SkuEntity> selectByExample(SkuEntityExample example) {
        List<SkuEntity> list = getSqlMapClientTemplate().queryForList("sku_entity.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public SkuEntity selectByPrimaryKey(Integer entityId) {
        SkuEntity _key = new SkuEntity();
        _key.setEntityId(entityId);
        SkuEntity record = (SkuEntity) getSqlMapClientTemplate().queryForObject("sku_entity.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int updateByExampleSelective(SkuEntity record, SkuEntityExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sku_entity.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int updateByExample(SkuEntity record, SkuEntityExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("sku_entity.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int updateByPrimaryKeySelective(SkuEntity record) {
        int rows = getSqlMapClientTemplate().update("sku_entity.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    public int updateByPrimaryKey(SkuEntity record) {
        int rows = getSqlMapClientTemplate().update("sku_entity.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sku_entity
     *
     * @mbggenerated
     */
    protected static class UpdateByExampleParms extends SkuEntityExample {
        private Object record;

        public UpdateByExampleParms(Object record, SkuEntityExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}