package com.ailk.ts.dal.ibatis.model;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ProductSkuExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected Integer limitClauseStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected Integer limitClauseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public ProductSkuExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected ProductSkuExample(ProductSkuExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void setLimitClauseStart(Integer limitClauseStart) {
        this.limitClauseStart = limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public Integer getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void setLimitClauseCount(Integer limitClauseCount) {
        this.limitClauseCount = limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public Integer getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_sku
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andSkuidIsNull() {
            addCriterion("SKUID is null");
            return (Criteria) this;
        }

        public Criteria andSkuidIsNotNull() {
            addCriterion("SKUID is not null");
            return (Criteria) this;
        }

        public Criteria andSkuidEqualTo(Integer value) {
            addCriterion("SKUID =", value, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidNotEqualTo(Integer value) {
            addCriterion("SKUID <>", value, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidGreaterThan(Integer value) {
            addCriterion("SKUID >", value, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidGreaterThanOrEqualTo(Integer value) {
            addCriterion("SKUID >=", value, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidLessThan(Integer value) {
            addCriterion("SKUID <", value, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidLessThanOrEqualTo(Integer value) {
            addCriterion("SKUID <=", value, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidIn(List<Integer> values) {
            addCriterion("SKUID in", values, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidNotIn(List<Integer> values) {
            addCriterion("SKUID not in", values, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidBetween(Integer value1, Integer value2) {
            addCriterion("SKUID between", value1, value2, "skuid");
            return (Criteria) this;
        }

        public Criteria andSkuidNotBetween(Integer value1, Integer value2) {
            addCriterion("SKUID not between", value1, value2, "skuid");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("PRODUCT_ID is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("PRODUCT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(Integer value) {
            addCriterion("PRODUCT_ID =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(Integer value) {
            addCriterion("PRODUCT_ID <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(Integer value) {
            addCriterion("PRODUCT_ID >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_ID >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(Integer value) {
            addCriterion("PRODUCT_ID <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(Integer value) {
            addCriterion("PRODUCT_ID <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<Integer> values) {
            addCriterion("PRODUCT_ID in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<Integer> values) {
            addCriterion("PRODUCT_ID not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_ID between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
            addCriterion("PRODUCT_ID not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNull() {
            addCriterion("SKU_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSkuNameIsNotNull() {
            addCriterion("SKU_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSkuNameEqualTo(String value) {
            addCriterion("SKU_NAME =", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotEqualTo(String value) {
            addCriterion("SKU_NAME <>", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThan(String value) {
            addCriterion("SKU_NAME >", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_NAME >=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThan(String value) {
            addCriterion("SKU_NAME <", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLessThanOrEqualTo(String value) {
            addCriterion("SKU_NAME <=", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameLike(String value) {
            addCriterion("SKU_NAME like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotLike(String value) {
            addCriterion("SKU_NAME not like", value, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameIn(List<String> values) {
            addCriterion("SKU_NAME in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotIn(List<String> values) {
            addCriterion("SKU_NAME not in", values, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameBetween(String value1, String value2) {
            addCriterion("SKU_NAME between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuNameNotBetween(String value1, String value2) {
            addCriterion("SKU_NAME not between", value1, value2, "skuName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameIsNull() {
            addCriterion("SKU_SUB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameIsNotNull() {
            addCriterion("SKU_SUB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameEqualTo(String value) {
            addCriterion("SKU_SUB_NAME =", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameNotEqualTo(String value) {
            addCriterion("SKU_SUB_NAME <>", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameGreaterThan(String value) {
            addCriterion("SKU_SUB_NAME >", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameGreaterThanOrEqualTo(String value) {
            addCriterion("SKU_SUB_NAME >=", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameLessThan(String value) {
            addCriterion("SKU_SUB_NAME <", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameLessThanOrEqualTo(String value) {
            addCriterion("SKU_SUB_NAME <=", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameLike(String value) {
            addCriterion("SKU_SUB_NAME like", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameNotLike(String value) {
            addCriterion("SKU_SUB_NAME not like", value, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameIn(List<String> values) {
            addCriterion("SKU_SUB_NAME in", values, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameNotIn(List<String> values) {
            addCriterion("SKU_SUB_NAME not in", values, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameBetween(String value1, String value2) {
            addCriterion("SKU_SUB_NAME between", value1, value2, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andSkuSubNameNotBetween(String value1, String value2) {
            addCriterion("SKU_SUB_NAME not between", value1, value2, "skuSubName");
            return (Criteria) this;
        }

        public Criteria andNormalPriceIsNull() {
            addCriterion("NORMAL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andNormalPriceIsNotNull() {
            addCriterion("NORMAL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andNormalPriceEqualTo(BigDecimal value) {
            addCriterion("NORMAL_PRICE =", value, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceNotEqualTo(BigDecimal value) {
            addCriterion("NORMAL_PRICE <>", value, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceGreaterThan(BigDecimal value) {
            addCriterion("NORMAL_PRICE >", value, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("NORMAL_PRICE >=", value, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceLessThan(BigDecimal value) {
            addCriterion("NORMAL_PRICE <", value, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("NORMAL_PRICE <=", value, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceIn(List<BigDecimal> values) {
            addCriterion("NORMAL_PRICE in", values, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceNotIn(List<BigDecimal> values) {
            addCriterion("NORMAL_PRICE not in", values, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NORMAL_PRICE between", value1, value2, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andNormalPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("NORMAL_PRICE not between", value1, value2, "normalPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceIsNull() {
            addCriterion("SAIL_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSailPriceIsNotNull() {
            addCriterion("SAIL_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSailPriceEqualTo(BigDecimal value) {
            addCriterion("SAIL_PRICE =", value, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceNotEqualTo(BigDecimal value) {
            addCriterion("SAIL_PRICE <>", value, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceGreaterThan(BigDecimal value) {
            addCriterion("SAIL_PRICE >", value, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SAIL_PRICE >=", value, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceLessThan(BigDecimal value) {
            addCriterion("SAIL_PRICE <", value, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SAIL_PRICE <=", value, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceIn(List<BigDecimal> values) {
            addCriterion("SAIL_PRICE in", values, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceNotIn(List<BigDecimal> values) {
            addCriterion("SAIL_PRICE not in", values, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SAIL_PRICE between", value1, value2, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andSailPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SAIL_PRICE not between", value1, value2, "sailPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceIsNull() {
            addCriterion("AGENT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andAgentPriceIsNotNull() {
            addCriterion("AGENT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andAgentPriceEqualTo(BigDecimal value) {
            addCriterion("AGENT_PRICE =", value, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceNotEqualTo(BigDecimal value) {
            addCriterion("AGENT_PRICE <>", value, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceGreaterThan(BigDecimal value) {
            addCriterion("AGENT_PRICE >", value, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("AGENT_PRICE >=", value, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceLessThan(BigDecimal value) {
            addCriterion("AGENT_PRICE <", value, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("AGENT_PRICE <=", value, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceIn(List<BigDecimal> values) {
            addCriterion("AGENT_PRICE in", values, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceNotIn(List<BigDecimal> values) {
            addCriterion("AGENT_PRICE not in", values, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGENT_PRICE between", value1, value2, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andAgentPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("AGENT_PRICE not between", value1, value2, "agentPrice");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("WEIGHT =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("WEIGHT <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("WEIGHT >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("WEIGHT >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("WEIGHT <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("WEIGHT <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("WEIGHT in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("WEIGHT not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andServiceMonthIsNull() {
            addCriterion("SERVICE_MONTH is null");
            return (Criteria) this;
        }

        public Criteria andServiceMonthIsNotNull() {
            addCriterion("SERVICE_MONTH is not null");
            return (Criteria) this;
        }

        public Criteria andServiceMonthEqualTo(Integer value) {
            addCriterion("SERVICE_MONTH =", value, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthNotEqualTo(Integer value) {
            addCriterion("SERVICE_MONTH <>", value, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthGreaterThan(Integer value) {
            addCriterion("SERVICE_MONTH >", value, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthGreaterThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_MONTH >=", value, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthLessThan(Integer value) {
            addCriterion("SERVICE_MONTH <", value, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthLessThanOrEqualTo(Integer value) {
            addCriterion("SERVICE_MONTH <=", value, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthIn(List<Integer> values) {
            addCriterion("SERVICE_MONTH in", values, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthNotIn(List<Integer> values) {
            addCriterion("SERVICE_MONTH not in", values, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_MONTH between", value1, value2, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andServiceMonthNotBetween(Integer value1, Integer value2) {
            addCriterion("SERVICE_MONTH not between", value1, value2, "serviceMonth");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSpeTypeIsNull() {
            addCriterion("SPE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSpeTypeIsNotNull() {
            addCriterion("SPE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSpeTypeEqualTo(String value) {
            addCriterion("SPE_TYPE =", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeNotEqualTo(String value) {
            addCriterion("SPE_TYPE <>", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeGreaterThan(String value) {
            addCriterion("SPE_TYPE >", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SPE_TYPE >=", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeLessThan(String value) {
            addCriterion("SPE_TYPE <", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeLessThanOrEqualTo(String value) {
            addCriterion("SPE_TYPE <=", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeLike(String value) {
            addCriterion("SPE_TYPE like", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeNotLike(String value) {
            addCriterion("SPE_TYPE not like", value, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeIn(List<String> values) {
            addCriterion("SPE_TYPE in", values, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeNotIn(List<String> values) {
            addCriterion("SPE_TYPE not in", values, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeBetween(String value1, String value2) {
            addCriterion("SPE_TYPE between", value1, value2, "speType");
            return (Criteria) this;
        }

        public Criteria andSpeTypeNotBetween(String value1, String value2) {
            addCriterion("SPE_TYPE not between", value1, value2, "speType");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNull() {
            addCriterion("CREATER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIsNotNull() {
            addCriterion("CREATER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterIdEqualTo(Integer value) {
            addCriterion("CREATER_ID =", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotEqualTo(Integer value) {
            addCriterion("CREATER_ID <>", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThan(Integer value) {
            addCriterion("CREATER_ID >", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATER_ID >=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThan(Integer value) {
            addCriterion("CREATER_ID <", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdLessThanOrEqualTo(Integer value) {
            addCriterion("CREATER_ID <=", value, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdIn(List<Integer> values) {
            addCriterion("CREATER_ID in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotIn(List<Integer> values) {
            addCriterion("CREATER_ID not in", values, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdBetween(Integer value1, Integer value2) {
            addCriterion("CREATER_ID between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreaterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATER_ID not between", value1, value2, "createrId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Timestamp value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Timestamp value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Timestamp> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifierIdIsNull() {
            addCriterion("MODIFIER_ID is null");
            return (Criteria) this;
        }

        public Criteria andModifierIdIsNotNull() {
            addCriterion("MODIFIER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andModifierIdEqualTo(Integer value) {
            addCriterion("MODIFIER_ID =", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotEqualTo(Integer value) {
            addCriterion("MODIFIER_ID <>", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdGreaterThan(Integer value) {
            addCriterion("MODIFIER_ID >", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("MODIFIER_ID >=", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLessThan(Integer value) {
            addCriterion("MODIFIER_ID <", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdLessThanOrEqualTo(Integer value) {
            addCriterion("MODIFIER_ID <=", value, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdIn(List<Integer> values) {
            addCriterion("MODIFIER_ID in", values, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotIn(List<Integer> values) {
            addCriterion("MODIFIER_ID not in", values, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdBetween(Integer value1, Integer value2) {
            addCriterion("MODIFIER_ID between", value1, value2, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifierIdNotBetween(Integer value1, Integer value2) {
            addCriterion("MODIFIER_ID not between", value1, value2, "modifierId");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("MODIFY_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("MODIFY_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(Timestamp value) {
            addCriterion("MODIFY_TIME >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(Timestamp value) {
            addCriterion("MODIFY_TIME <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("MODIFY_TIME <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<Timestamp> values) {
            addCriterion("MODIFY_TIME in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<Timestamp> values) {
            addCriterion("MODIFY_TIME not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("MODIFY_TIME between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("MODIFY_TIME not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneIsNull() {
            addCriterion("IS_RANGEPHONE is null");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneIsNotNull() {
            addCriterion("IS_RANGEPHONE is not null");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneEqualTo(String value) {
            addCriterion("IS_RANGEPHONE =", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneNotEqualTo(String value) {
            addCriterion("IS_RANGEPHONE <>", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneGreaterThan(String value) {
            addCriterion("IS_RANGEPHONE >", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneGreaterThanOrEqualTo(String value) {
            addCriterion("IS_RANGEPHONE >=", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneLessThan(String value) {
            addCriterion("IS_RANGEPHONE <", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneLessThanOrEqualTo(String value) {
            addCriterion("IS_RANGEPHONE <=", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneLike(String value) {
            addCriterion("IS_RANGEPHONE like", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneNotLike(String value) {
            addCriterion("IS_RANGEPHONE not like", value, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneIn(List<String> values) {
            addCriterion("IS_RANGEPHONE in", values, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneNotIn(List<String> values) {
            addCriterion("IS_RANGEPHONE not in", values, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneBetween(String value1, String value2) {
            addCriterion("IS_RANGEPHONE between", value1, value2, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andIsRangephoneNotBetween(String value1, String value2) {
            addCriterion("IS_RANGEPHONE not between", value1, value2, "isRangephone");
            return (Criteria) this;
        }

        public Criteria andRangePriceIsNull() {
            addCriterion("RANGE_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andRangePriceIsNotNull() {
            addCriterion("RANGE_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andRangePriceEqualTo(BigDecimal value) {
            addCriterion("RANGE_PRICE =", value, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceNotEqualTo(BigDecimal value) {
            addCriterion("RANGE_PRICE <>", value, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceGreaterThan(BigDecimal value) {
            addCriterion("RANGE_PRICE >", value, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RANGE_PRICE >=", value, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceLessThan(BigDecimal value) {
            addCriterion("RANGE_PRICE <", value, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RANGE_PRICE <=", value, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceIn(List<BigDecimal> values) {
            addCriterion("RANGE_PRICE in", values, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceNotIn(List<BigDecimal> values) {
            addCriterion("RANGE_PRICE not in", values, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RANGE_PRICE between", value1, value2, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andRangePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RANGE_PRICE not between", value1, value2, "rangePrice");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("COMMENTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("COMMENTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("COMMENTS =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("COMMENTS <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("COMMENTS >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENTS >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("COMMENTS <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("COMMENTS <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("COMMENTS like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("COMMENTS not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("COMMENTS in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("COMMENTS not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("COMMENTS between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("COMMENTS not between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andListpicIsNull() {
            addCriterion("LISTPIC is null");
            return (Criteria) this;
        }

        public Criteria andListpicIsNotNull() {
            addCriterion("LISTPIC is not null");
            return (Criteria) this;
        }

        public Criteria andListpicEqualTo(Long value) {
            addCriterion("LISTPIC =", value, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicNotEqualTo(Long value) {
            addCriterion("LISTPIC <>", value, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicGreaterThan(Long value) {
            addCriterion("LISTPIC >", value, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicGreaterThanOrEqualTo(Long value) {
            addCriterion("LISTPIC >=", value, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicLessThan(Long value) {
            addCriterion("LISTPIC <", value, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicLessThanOrEqualTo(Long value) {
            addCriterion("LISTPIC <=", value, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicIn(List<Long> values) {
            addCriterion("LISTPIC in", values, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicNotIn(List<Long> values) {
            addCriterion("LISTPIC not in", values, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicBetween(Long value1, Long value2) {
            addCriterion("LISTPIC between", value1, value2, "listpic");
            return (Criteria) this;
        }

        public Criteria andListpicNotBetween(Long value1, Long value2) {
            addCriterion("LISTPIC not between", value1, value2, "listpic");
            return (Criteria) this;
        }

        public Criteria andGoodTypeIsNull() {
            addCriterion("GOOD_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andGoodTypeIsNotNull() {
            addCriterion("GOOD_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andGoodTypeEqualTo(String value) {
            addCriterion("GOOD_TYPE =", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeNotEqualTo(String value) {
            addCriterion("GOOD_TYPE <>", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeGreaterThan(String value) {
            addCriterion("GOOD_TYPE >", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeGreaterThanOrEqualTo(String value) {
            addCriterion("GOOD_TYPE >=", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeLessThan(String value) {
            addCriterion("GOOD_TYPE <", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeLessThanOrEqualTo(String value) {
            addCriterion("GOOD_TYPE <=", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeLike(String value) {
            addCriterion("GOOD_TYPE like", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeNotLike(String value) {
            addCriterion("GOOD_TYPE not like", value, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeIn(List<String> values) {
            addCriterion("GOOD_TYPE in", values, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeNotIn(List<String> values) {
            addCriterion("GOOD_TYPE not in", values, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeBetween(String value1, String value2) {
            addCriterion("GOOD_TYPE between", value1, value2, "goodType");
            return (Criteria) this;
        }

        public Criteria andGoodTypeNotBetween(String value1, String value2) {
            addCriterion("GOOD_TYPE not between", value1, value2, "goodType");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdIsNull() {
            addCriterion("BSS_GOOD_ID is null");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdIsNotNull() {
            addCriterion("BSS_GOOD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdEqualTo(String value) {
            addCriterion("BSS_GOOD_ID =", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdNotEqualTo(String value) {
            addCriterion("BSS_GOOD_ID <>", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdGreaterThan(String value) {
            addCriterion("BSS_GOOD_ID >", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdGreaterThanOrEqualTo(String value) {
            addCriterion("BSS_GOOD_ID >=", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdLessThan(String value) {
            addCriterion("BSS_GOOD_ID <", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdLessThanOrEqualTo(String value) {
            addCriterion("BSS_GOOD_ID <=", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdLike(String value) {
            addCriterion("BSS_GOOD_ID like", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdNotLike(String value) {
            addCriterion("BSS_GOOD_ID not like", value, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdIn(List<String> values) {
            addCriterion("BSS_GOOD_ID in", values, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdNotIn(List<String> values) {
            addCriterion("BSS_GOOD_ID not in", values, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdBetween(String value1, String value2) {
            addCriterion("BSS_GOOD_ID between", value1, value2, "bssGoodId");
            return (Criteria) this;
        }

        public Criteria andBssGoodIdNotBetween(String value1, String value2) {
            addCriterion("BSS_GOOD_ID not between", value1, value2, "bssGoodId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product_sku
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}