package com.ailk.ts.dal.ibatis.model;

public class Rep {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep.SKUID
     *
     * @mbggenerated
     */
    private Integer skuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep.REPOSITORY_CODE
     *
     * @mbggenerated
     */
    private String repositoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep.COUNT
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep.ID
     *
     * @return the value of rep.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep.ID
     *
     * @param id the value for rep.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep.SKUID
     *
     * @return the value of rep.SKUID
     *
     * @mbggenerated
     */
    public Integer getSkuid() {
        return skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep.SKUID
     *
     * @param skuid the value for rep.SKUID
     *
     * @mbggenerated
     */
    public void setSkuid(Integer skuid) {
        this.skuid = skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep.REPOSITORY_CODE
     *
     * @return the value of rep.REPOSITORY_CODE
     *
     * @mbggenerated
     */
    public String getRepositoryCode() {
        return repositoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep.REPOSITORY_CODE
     *
     * @param repositoryCode the value for rep.REPOSITORY_CODE
     *
     * @mbggenerated
     */
    public void setRepositoryCode(String repositoryCode) {
        this.repositoryCode = repositoryCode == null ? null : repositoryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep.COUNT
     *
     * @return the value of rep.COUNT
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep.COUNT
     *
     * @param count the value for rep.COUNT
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }
}