package com.ailk.ts.dal.ibatis.model;

import java.sql.Timestamp;

public class RepOptRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.SERIAL_NO
     *
     * @mbggenerated
     */
    private Long serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.INPUT_REP_CODE
     *
     * @mbggenerated
     */
    private Long inputRepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.OUTPUT_REP_CODE
     *
     * @mbggenerated
     */
    private Long outputRepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.SKUID
     *
     * @mbggenerated
     */
    private Long skuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.OPT_TYPE
     *
     * @mbggenerated
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.COUNT
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.CREATE_TIME
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.OPT_ID
     *
     * @mbggenerated
     */
    private Long optId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.SERIAL_NO
     *
     * @return the value of rep_opt_record.SERIAL_NO
     *
     * @mbggenerated
     */
    public Long getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.SERIAL_NO
     *
     * @param serialNo the value for rep_opt_record.SERIAL_NO
     *
     * @mbggenerated
     */
    public void setSerialNo(Long serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.INPUT_REP_CODE
     *
     * @return the value of rep_opt_record.INPUT_REP_CODE
     *
     * @mbggenerated
     */
    public Long getInputRepCode() {
        return inputRepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.INPUT_REP_CODE
     *
     * @param inputRepCode the value for rep_opt_record.INPUT_REP_CODE
     *
     * @mbggenerated
     */
    public void setInputRepCode(Long inputRepCode) {
        this.inputRepCode = inputRepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.OUTPUT_REP_CODE
     *
     * @return the value of rep_opt_record.OUTPUT_REP_CODE
     *
     * @mbggenerated
     */
    public Long getOutputRepCode() {
        return outputRepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.OUTPUT_REP_CODE
     *
     * @param outputRepCode the value for rep_opt_record.OUTPUT_REP_CODE
     *
     * @mbggenerated
     */
    public void setOutputRepCode(Long outputRepCode) {
        this.outputRepCode = outputRepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.SKUID
     *
     * @return the value of rep_opt_record.SKUID
     *
     * @mbggenerated
     */
    public Long getSkuid() {
        return skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.SKUID
     *
     * @param skuid the value for rep_opt_record.SKUID
     *
     * @mbggenerated
     */
    public void setSkuid(Long skuid) {
        this.skuid = skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.OPT_TYPE
     *
     * @return the value of rep_opt_record.OPT_TYPE
     *
     * @mbggenerated
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.OPT_TYPE
     *
     * @param optType the value for rep_opt_record.OPT_TYPE
     *
     * @mbggenerated
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.COUNT
     *
     * @return the value of rep_opt_record.COUNT
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.COUNT
     *
     * @param count the value for rep_opt_record.COUNT
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.CREATE_TIME
     *
     * @return the value of rep_opt_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.CREATE_TIME
     *
     * @param createTime the value for rep_opt_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.OPT_ID
     *
     * @return the value of rep_opt_record.OPT_ID
     *
     * @mbggenerated
     */
    public Long getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.OPT_ID
     *
     * @param optId the value for rep_opt_record.OPT_ID
     *
     * @mbggenerated
     */
    public void setOptId(Long optId) {
        this.optId = optId;
    }
}