package com.ailk.ts.dal.ibatis.model;

import java.sql.Timestamp;

public class RepOptRecord {
	
	private String repName;
	private String optName;
	private String skuName;
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.SERIAL_NO
     *
     * @mbggenerated
     */
    private Integer serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.INPUT_REP_CODE
     *
     * @mbggenerated
     */
    private String inputRepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.OUTPUT_REP_CODE
     *
     * @mbggenerated
     */
    private String outputRepCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.SKUID
     *
     * @mbggenerated
     */
    private Integer skuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.OPT_TYPE
     *
     * @mbggenerated
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.COUNT
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.CREATE_TIME
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_opt_record.OPT_ID
     *
     * @mbggenerated
     */
    private Integer optId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.SERIAL_NO
     *
     * @return the value of rep_opt_record.SERIAL_NO
     *
     * @mbggenerated
     */
    public Integer getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.SERIAL_NO
     *
     * @param serialNo the value for rep_opt_record.SERIAL_NO
     *
     * @mbggenerated
     */
    public void setSerialNo(Integer serialNo) {
        this.serialNo = serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.INPUT_REP_CODE
     *
     * @return the value of rep_opt_record.INPUT_REP_CODE
     *
     * @mbggenerated
     */
    public String getInputRepCode() {
        return inputRepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.INPUT_REP_CODE
     *
     * @param inputRepCode the value for rep_opt_record.INPUT_REP_CODE
     *
     * @mbggenerated
     */
    public void setInputRepCode(String inputRepCode) {
        this.inputRepCode = inputRepCode == null ? null : inputRepCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.OUTPUT_REP_CODE
     *
     * @return the value of rep_opt_record.OUTPUT_REP_CODE
     *
     * @mbggenerated
     */
    public String getOutputRepCode() {
        return outputRepCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.OUTPUT_REP_CODE
     *
     * @param outputRepCode the value for rep_opt_record.OUTPUT_REP_CODE
     *
     * @mbggenerated
     */
    public void setOutputRepCode(String outputRepCode) {
        this.outputRepCode = outputRepCode == null ? null : outputRepCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.SKUID
     *
     * @return the value of rep_opt_record.SKUID
     *
     * @mbggenerated
     */
    public Integer getSkuid() {
        return skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.SKUID
     *
     * @param skuid the value for rep_opt_record.SKUID
     *
     * @mbggenerated
     */
    public void setSkuid(Integer skuid) {
        this.skuid = skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.OPT_TYPE
     *
     * @return the value of rep_opt_record.OPT_TYPE
     *
     * @mbggenerated
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.OPT_TYPE
     *
     * @param optType the value for rep_opt_record.OPT_TYPE
     *
     * @mbggenerated
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.COUNT
     *
     * @return the value of rep_opt_record.COUNT
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.COUNT
     *
     * @param count the value for rep_opt_record.COUNT
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.CREATE_TIME
     *
     * @return the value of rep_opt_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.CREATE_TIME
     *
     * @param createTime the value for rep_opt_record.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_opt_record.OPT_ID
     *
     * @return the value of rep_opt_record.OPT_ID
     *
     * @mbggenerated
     */
    public Integer getOptId() {
        return optId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_opt_record.OPT_ID
     *
     * @param optId the value for rep_opt_record.OPT_ID
     *
     * @mbggenerated
     */
    public void setOptId(Integer optId) {
        this.optId = optId;
    }

	public String getRepName() {
		return repName;
	}

	public void setRepName(String repName) {
		this.repName = repName;
	}

	public String getOptName() {
		return optName;
	}

	public void setOptName(String optName) {
		this.optName = optName;
	}

	public String getSkuName() {
		return skuName;
	}

	public void setSkuName(String skuName) {
		this.skuName = skuName;
	}
}