package com.ailk.ts.dal.ibatis.model;

import java.sql.Timestamp;

public class Repository {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.REP_CODE
     *
     * @mbggenerated
     */
    private Long repCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.REP_NAME
     *
     * @mbggenerated
     */
    private String repName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.DEPT_ID
     *
     * @mbggenerated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.CREATE_TIME
     *
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.PROVINCE
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.AREA
     *
     * @mbggenerated
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.COUNTY
     *
     * @mbggenerated
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.STREET
     *
     * @mbggenerated
     */
    private String street;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repository.USER_ID
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.REP_CODE
     *
     * @return the value of repository.REP_CODE
     *
     * @mbggenerated
     */
    public Long getRepCode() {
        return repCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.REP_CODE
     *
     * @param repCode the value for repository.REP_CODE
     *
     * @mbggenerated
     */
    public void setRepCode(Long repCode) {
        this.repCode = repCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.REP_NAME
     *
     * @return the value of repository.REP_NAME
     *
     * @mbggenerated
     */
    public String getRepName() {
        return repName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.REP_NAME
     *
     * @param repName the value for repository.REP_NAME
     *
     * @mbggenerated
     */
    public void setRepName(String repName) {
        this.repName = repName == null ? null : repName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.DEPT_ID
     *
     * @return the value of repository.DEPT_ID
     *
     * @mbggenerated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.DEPT_ID
     *
     * @param deptId the value for repository.DEPT_ID
     *
     * @mbggenerated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.CREATE_TIME
     *
     * @return the value of repository.CREATE_TIME
     *
     * @mbggenerated
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.CREATE_TIME
     *
     * @param createTime the value for repository.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.PROVINCE
     *
     * @return the value of repository.PROVINCE
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.PROVINCE
     *
     * @param province the value for repository.PROVINCE
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.AREA
     *
     * @return the value of repository.AREA
     *
     * @mbggenerated
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.AREA
     *
     * @param area the value for repository.AREA
     *
     * @mbggenerated
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.COUNTY
     *
     * @return the value of repository.COUNTY
     *
     * @mbggenerated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.COUNTY
     *
     * @param county the value for repository.COUNTY
     *
     * @mbggenerated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.STREET
     *
     * @return the value of repository.STREET
     *
     * @mbggenerated
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.STREET
     *
     * @param street the value for repository.STREET
     *
     * @mbggenerated
     */
    public void setStreet(String street) {
        this.street = street == null ? null : street.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.REMARK
     *
     * @return the value of repository.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.REMARK
     *
     * @param remark the value for repository.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repository.USER_ID
     *
     * @return the value of repository.USER_ID
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repository.USER_ID
     *
     * @param userId the value for repository.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }
}