package com.ailk.ts.dal.ibatis.model;

import java.sql.Timestamp;

public class RepSellDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.RID
     *
     * @mbggenerated
     */
    private Long rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.ENTITY_ID
     *
     * @mbggenerated
     */
    private Long entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.REP_OPT_ID
     *
     * @mbggenerated
     */
    private Long repOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.ORDER_ID
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.OPT_TYPE
     *
     * @mbggenerated
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.OPTER_ID
     *
     * @mbggenerated
     */
    private Long opterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.OPT_TIME
     *
     * @mbggenerated
     */
    private Timestamp optTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_sell_detail.ORDER_DOMAIN
     *
     * @mbggenerated
     */
    private String orderDomain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.RID
     *
     * @return the value of rep_sell_detail.RID
     *
     * @mbggenerated
     */
    public Long getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.RID
     *
     * @param rid the value for rep_sell_detail.RID
     *
     * @mbggenerated
     */
    public void setRid(Long rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.ENTITY_ID
     *
     * @return the value of rep_sell_detail.ENTITY_ID
     *
     * @mbggenerated
     */
    public Long getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.ENTITY_ID
     *
     * @param entityId the value for rep_sell_detail.ENTITY_ID
     *
     * @mbggenerated
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.REP_OPT_ID
     *
     * @return the value of rep_sell_detail.REP_OPT_ID
     *
     * @mbggenerated
     */
    public Long getRepOptId() {
        return repOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.REP_OPT_ID
     *
     * @param repOptId the value for rep_sell_detail.REP_OPT_ID
     *
     * @mbggenerated
     */
    public void setRepOptId(Long repOptId) {
        this.repOptId = repOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.ORDER_ID
     *
     * @return the value of rep_sell_detail.ORDER_ID
     *
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.ORDER_ID
     *
     * @param orderId the value for rep_sell_detail.ORDER_ID
     *
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.OPT_TYPE
     *
     * @return the value of rep_sell_detail.OPT_TYPE
     *
     * @mbggenerated
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.OPT_TYPE
     *
     * @param optType the value for rep_sell_detail.OPT_TYPE
     *
     * @mbggenerated
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.OPTER_ID
     *
     * @return the value of rep_sell_detail.OPTER_ID
     *
     * @mbggenerated
     */
    public Long getOpterId() {
        return opterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.OPTER_ID
     *
     * @param opterId the value for rep_sell_detail.OPTER_ID
     *
     * @mbggenerated
     */
    public void setOpterId(Long opterId) {
        this.opterId = opterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.OPT_TIME
     *
     * @return the value of rep_sell_detail.OPT_TIME
     *
     * @mbggenerated
     */
    public Timestamp getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.OPT_TIME
     *
     * @param optTime the value for rep_sell_detail.OPT_TIME
     *
     * @mbggenerated
     */
    public void setOptTime(Timestamp optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_sell_detail.ORDER_DOMAIN
     *
     * @return the value of rep_sell_detail.ORDER_DOMAIN
     *
     * @mbggenerated
     */
    public String getOrderDomain() {
        return orderDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_sell_detail.ORDER_DOMAIN
     *
     * @param orderDomain the value for rep_sell_detail.ORDER_DOMAIN
     *
     * @mbggenerated
     */
    public void setOrderDomain(String orderDomain) {
        this.orderDomain = orderDomain == null ? null : orderDomain.trim();
    }
}