package com.ailk.ts.dal.ibatis.model;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class RepSellDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected Integer limitClauseStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected Integer limitClauseCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public RepSellDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected RepSellDetailExample(RepSellDetailExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
        this.distinct = example.distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void setLimitClauseStart(Integer limitClauseStart) {
        this.limitClauseStart = limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public Integer getLimitClauseStart() {
        return limitClauseStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void setLimitClauseCount(Integer limitClauseCount) {
        this.limitClauseCount = limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public Integer getLimitClauseCount() {
        return limitClauseCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rep_sell_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected GeneratedCriteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andRidIsNull() {
            addCriterion("RID is null");
            return (Criteria) this;
        }

        public Criteria andRidIsNotNull() {
            addCriterion("RID is not null");
            return (Criteria) this;
        }

        public Criteria andRidEqualTo(Integer value) {
            addCriterion("RID =", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotEqualTo(Integer value) {
            addCriterion("RID <>", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThan(Integer value) {
            addCriterion("RID >", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidGreaterThanOrEqualTo(Integer value) {
            addCriterion("RID >=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThan(Integer value) {
            addCriterion("RID <", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidLessThanOrEqualTo(Integer value) {
            addCriterion("RID <=", value, "rid");
            return (Criteria) this;
        }

        public Criteria andRidIn(List<Integer> values) {
            addCriterion("RID in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotIn(List<Integer> values) {
            addCriterion("RID not in", values, "rid");
            return (Criteria) this;
        }

        public Criteria andRidBetween(Integer value1, Integer value2) {
            addCriterion("RID between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andRidNotBetween(Integer value1, Integer value2) {
            addCriterion("RID not between", value1, value2, "rid");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNull() {
            addCriterion("ENTITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andEntityIdIsNotNull() {
            addCriterion("ENTITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEntityIdEqualTo(Integer value) {
            addCriterion("ENTITY_ID =", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotEqualTo(Integer value) {
            addCriterion("ENTITY_ID <>", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThan(Integer value) {
            addCriterion("ENTITY_ID >", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ENTITY_ID >=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThan(Integer value) {
            addCriterion("ENTITY_ID <", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdLessThanOrEqualTo(Integer value) {
            addCriterion("ENTITY_ID <=", value, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdIn(List<Integer> values) {
            addCriterion("ENTITY_ID in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotIn(List<Integer> values) {
            addCriterion("ENTITY_ID not in", values, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdBetween(Integer value1, Integer value2) {
            addCriterion("ENTITY_ID between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andEntityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ENTITY_ID not between", value1, value2, "entityId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdIsNull() {
            addCriterion("REP_OPT_ID is null");
            return (Criteria) this;
        }

        public Criteria andRepOptIdIsNotNull() {
            addCriterion("REP_OPT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRepOptIdEqualTo(Integer value) {
            addCriterion("REP_OPT_ID =", value, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdNotEqualTo(Integer value) {
            addCriterion("REP_OPT_ID <>", value, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdGreaterThan(Integer value) {
            addCriterion("REP_OPT_ID >", value, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("REP_OPT_ID >=", value, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdLessThan(Integer value) {
            addCriterion("REP_OPT_ID <", value, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdLessThanOrEqualTo(Integer value) {
            addCriterion("REP_OPT_ID <=", value, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdIn(List<Integer> values) {
            addCriterion("REP_OPT_ID in", values, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdNotIn(List<Integer> values) {
            addCriterion("REP_OPT_ID not in", values, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdBetween(Integer value1, Integer value2) {
            addCriterion("REP_OPT_ID between", value1, value2, "repOptId");
            return (Criteria) this;
        }

        public Criteria andRepOptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("REP_OPT_ID not between", value1, value2, "repOptId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOptTypeIsNull() {
            addCriterion("OPT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOptTypeIsNotNull() {
            addCriterion("OPT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOptTypeEqualTo(String value) {
            addCriterion("OPT_TYPE =", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeNotEqualTo(String value) {
            addCriterion("OPT_TYPE <>", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeGreaterThan(String value) {
            addCriterion("OPT_TYPE >", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OPT_TYPE >=", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeLessThan(String value) {
            addCriterion("OPT_TYPE <", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeLessThanOrEqualTo(String value) {
            addCriterion("OPT_TYPE <=", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeLike(String value) {
            addCriterion("OPT_TYPE like", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeNotLike(String value) {
            addCriterion("OPT_TYPE not like", value, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeIn(List<String> values) {
            addCriterion("OPT_TYPE in", values, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeNotIn(List<String> values) {
            addCriterion("OPT_TYPE not in", values, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeBetween(String value1, String value2) {
            addCriterion("OPT_TYPE between", value1, value2, "optType");
            return (Criteria) this;
        }

        public Criteria andOptTypeNotBetween(String value1, String value2) {
            addCriterion("OPT_TYPE not between", value1, value2, "optType");
            return (Criteria) this;
        }

        public Criteria andOpterIdIsNull() {
            addCriterion("OPTER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOpterIdIsNotNull() {
            addCriterion("OPTER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOpterIdEqualTo(Integer value) {
            addCriterion("OPTER_ID =", value, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdNotEqualTo(Integer value) {
            addCriterion("OPTER_ID <>", value, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdGreaterThan(Integer value) {
            addCriterion("OPTER_ID >", value, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("OPTER_ID >=", value, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdLessThan(Integer value) {
            addCriterion("OPTER_ID <", value, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdLessThanOrEqualTo(Integer value) {
            addCriterion("OPTER_ID <=", value, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdIn(List<Integer> values) {
            addCriterion("OPTER_ID in", values, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdNotIn(List<Integer> values) {
            addCriterion("OPTER_ID not in", values, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdBetween(Integer value1, Integer value2) {
            addCriterion("OPTER_ID between", value1, value2, "opterId");
            return (Criteria) this;
        }

        public Criteria andOpterIdNotBetween(Integer value1, Integer value2) {
            addCriterion("OPTER_ID not between", value1, value2, "opterId");
            return (Criteria) this;
        }

        public Criteria andOptTimeIsNull() {
            addCriterion("OPT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andOptTimeIsNotNull() {
            addCriterion("OPT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andOptTimeEqualTo(Timestamp value) {
            addCriterion("OPT_TIME =", value, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeNotEqualTo(Timestamp value) {
            addCriterion("OPT_TIME <>", value, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeGreaterThan(Timestamp value) {
            addCriterion("OPT_TIME >", value, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("OPT_TIME >=", value, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeLessThan(Timestamp value) {
            addCriterion("OPT_TIME <", value, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("OPT_TIME <=", value, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeIn(List<Timestamp> values) {
            addCriterion("OPT_TIME in", values, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeNotIn(List<Timestamp> values) {
            addCriterion("OPT_TIME not in", values, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("OPT_TIME between", value1, value2, "optTime");
            return (Criteria) this;
        }

        public Criteria andOptTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("OPT_TIME not between", value1, value2, "optTime");
            return (Criteria) this;
        }

        public Criteria andOrderDomainIsNull() {
            addCriterion("ORDER_DOMAIN is null");
            return (Criteria) this;
        }

        public Criteria andOrderDomainIsNotNull() {
            addCriterion("ORDER_DOMAIN is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDomainEqualTo(String value) {
            addCriterion("ORDER_DOMAIN =", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainNotEqualTo(String value) {
            addCriterion("ORDER_DOMAIN <>", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainGreaterThan(String value) {
            addCriterion("ORDER_DOMAIN >", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_DOMAIN >=", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainLessThan(String value) {
            addCriterion("ORDER_DOMAIN <", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainLessThanOrEqualTo(String value) {
            addCriterion("ORDER_DOMAIN <=", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainLike(String value) {
            addCriterion("ORDER_DOMAIN like", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainNotLike(String value) {
            addCriterion("ORDER_DOMAIN not like", value, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainIn(List<String> values) {
            addCriterion("ORDER_DOMAIN in", values, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainNotIn(List<String> values) {
            addCriterion("ORDER_DOMAIN not in", values, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainBetween(String value1, String value2) {
            addCriterion("ORDER_DOMAIN between", value1, value2, "orderDomain");
            return (Criteria) this;
        }

        public Criteria andOrderDomainNotBetween(String value1, String value2) {
            addCriterion("ORDER_DOMAIN not between", value1, value2, "orderDomain");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rep_sell_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}