package com.ailk.ts.dal.ibatis.model;

import java.sql.Timestamp;

public class RepStockDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_stock_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    private Integer detailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_stock_detail.REP_OPT_ID
     *
     * @mbggenerated
     */
    private Integer repOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_stock_detail.ENTITY_ID
     *
     * @mbggenerated
     */
    private Integer entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_stock_detail.OPT_TYPE
     *
     * @mbggenerated
     */
    private String optType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_stock_detail.OPTER_ID
     *
     * @mbggenerated
     */
    private Integer opterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rep_stock_detail.OPT_TIME
     *
     * @mbggenerated
     */
    private Timestamp optTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_stock_detail.DETAIL_ID
     *
     * @return the value of rep_stock_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_stock_detail.DETAIL_ID
     *
     * @param detailId the value for rep_stock_detail.DETAIL_ID
     *
     * @mbggenerated
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_stock_detail.REP_OPT_ID
     *
     * @return the value of rep_stock_detail.REP_OPT_ID
     *
     * @mbggenerated
     */
    public Integer getRepOptId() {
        return repOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_stock_detail.REP_OPT_ID
     *
     * @param repOptId the value for rep_stock_detail.REP_OPT_ID
     *
     * @mbggenerated
     */
    public void setRepOptId(Integer repOptId) {
        this.repOptId = repOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_stock_detail.ENTITY_ID
     *
     * @return the value of rep_stock_detail.ENTITY_ID
     *
     * @mbggenerated
     */
    public Integer getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_stock_detail.ENTITY_ID
     *
     * @param entityId the value for rep_stock_detail.ENTITY_ID
     *
     * @mbggenerated
     */
    public void setEntityId(Integer entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_stock_detail.OPT_TYPE
     *
     * @return the value of rep_stock_detail.OPT_TYPE
     *
     * @mbggenerated
     */
    public String getOptType() {
        return optType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_stock_detail.OPT_TYPE
     *
     * @param optType the value for rep_stock_detail.OPT_TYPE
     *
     * @mbggenerated
     */
    public void setOptType(String optType) {
        this.optType = optType == null ? null : optType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_stock_detail.OPTER_ID
     *
     * @return the value of rep_stock_detail.OPTER_ID
     *
     * @mbggenerated
     */
    public Integer getOpterId() {
        return opterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_stock_detail.OPTER_ID
     *
     * @param opterId the value for rep_stock_detail.OPTER_ID
     *
     * @mbggenerated
     */
    public void setOpterId(Integer opterId) {
        this.opterId = opterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rep_stock_detail.OPT_TIME
     *
     * @return the value of rep_stock_detail.OPT_TIME
     *
     * @mbggenerated
     */
    public Timestamp getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rep_stock_detail.OPT_TIME
     *
     * @param optTime the value for rep_stock_detail.OPT_TIME
     *
     * @mbggenerated
     */
    public void setOptTime(Timestamp optTime) {
        this.optTime = optTime;
    }
}