package com.ailk.ts.dal.ibatis.model;

import java.math.BigDecimal;
import java.sql.Timestamp;

public class SkuEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.ENTITY_ID
     *
     * @mbggenerated
     */
    private Long entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.SKUID
     *
     * @mbggenerated
     */
    private Long skuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.REPOSITORY_CODE
     *
     * @mbggenerated
     */
    private Long repositoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.IMEI
     *
     * @mbggenerated
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.SERIAL
     *
     * @mbggenerated
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.COST_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.SELL_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal sellPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.MODIFY_TIME
     *
     * @mbggenerated
     */
    private Timestamp modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.SERVICE_START
     *
     * @mbggenerated
     */
    private Timestamp serviceStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.SERVICE_END
     *
     * @mbggenerated
     */
    private Timestamp serviceEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_entity.TARGET_REPCODE
     *
     * @mbggenerated
     */
    private Long targetRepcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.ENTITY_ID
     *
     * @return the value of sku_entity.ENTITY_ID
     *
     * @mbggenerated
     */
    public Long getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.ENTITY_ID
     *
     * @param entityId the value for sku_entity.ENTITY_ID
     *
     * @mbggenerated
     */
    public void setEntityId(Long entityId) {
        this.entityId = entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.SKUID
     *
     * @return the value of sku_entity.SKUID
     *
     * @mbggenerated
     */
    public Long getSkuid() {
        return skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.SKUID
     *
     * @param skuid the value for sku_entity.SKUID
     *
     * @mbggenerated
     */
    public void setSkuid(Long skuid) {
        this.skuid = skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.REPOSITORY_CODE
     *
     * @return the value of sku_entity.REPOSITORY_CODE
     *
     * @mbggenerated
     */
    public Long getRepositoryCode() {
        return repositoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.REPOSITORY_CODE
     *
     * @param repositoryCode the value for sku_entity.REPOSITORY_CODE
     *
     * @mbggenerated
     */
    public void setRepositoryCode(Long repositoryCode) {
        this.repositoryCode = repositoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.IMEI
     *
     * @return the value of sku_entity.IMEI
     *
     * @mbggenerated
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.IMEI
     *
     * @param imei the value for sku_entity.IMEI
     *
     * @mbggenerated
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.SERIAL
     *
     * @return the value of sku_entity.SERIAL
     *
     * @mbggenerated
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.SERIAL
     *
     * @param serial the value for sku_entity.SERIAL
     *
     * @mbggenerated
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.COST_PRICE
     *
     * @return the value of sku_entity.COST_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.COST_PRICE
     *
     * @param costPrice the value for sku_entity.COST_PRICE
     *
     * @mbggenerated
     */
    public void setCostPrice(BigDecimal costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.SELL_PRICE
     *
     * @return the value of sku_entity.SELL_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getSellPrice() {
        return sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.SELL_PRICE
     *
     * @param sellPrice the value for sku_entity.SELL_PRICE
     *
     * @mbggenerated
     */
    public void setSellPrice(BigDecimal sellPrice) {
        this.sellPrice = sellPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.STATUS
     *
     * @return the value of sku_entity.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.STATUS
     *
     * @param status the value for sku_entity.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.MODIFY_TIME
     *
     * @return the value of sku_entity.MODIFY_TIME
     *
     * @mbggenerated
     */
    public Timestamp getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.MODIFY_TIME
     *
     * @param modifyTime the value for sku_entity.MODIFY_TIME
     *
     * @mbggenerated
     */
    public void setModifyTime(Timestamp modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.SERVICE_START
     *
     * @return the value of sku_entity.SERVICE_START
     *
     * @mbggenerated
     */
    public Timestamp getServiceStart() {
        return serviceStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.SERVICE_START
     *
     * @param serviceStart the value for sku_entity.SERVICE_START
     *
     * @mbggenerated
     */
    public void setServiceStart(Timestamp serviceStart) {
        this.serviceStart = serviceStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.SERVICE_END
     *
     * @return the value of sku_entity.SERVICE_END
     *
     * @mbggenerated
     */
    public Timestamp getServiceEnd() {
        return serviceEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.SERVICE_END
     *
     * @param serviceEnd the value for sku_entity.SERVICE_END
     *
     * @mbggenerated
     */
    public void setServiceEnd(Timestamp serviceEnd) {
        this.serviceEnd = serviceEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sku_entity.TARGET_REPCODE
     *
     * @return the value of sku_entity.TARGET_REPCODE
     *
     * @mbggenerated
     */
    public Long getTargetRepcode() {
        return targetRepcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sku_entity.TARGET_REPCODE
     *
     * @param targetRepcode the value for sku_entity.TARGET_REPCODE
     *
     * @mbggenerated
     */
    public void setTargetRepcode(Long targetRepcode) {
        this.targetRepcode = targetRepcode;
    }
}